version: 2

updates:
  - package-ecosystem: gitsubmodule
    schedule:
        interval: "daily"
    directory: /
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"