//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlphaOmega.Debug {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AttributeNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AttributeNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AlphaOmega.Debug.AttributeNames", typeof(AttributeNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raw Read Error Rate.
        /// </summary>
        internal static string _0x01 {
            get {
                return ResourceManager.GetString("0x01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Throughput Performance.
        /// </summary>
        internal static string _0x02 {
            get {
                return ResourceManager.GetString("0x02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spin-Up Time.
        /// </summary>
        internal static string _0x03 {
            get {
                return ResourceManager.GetString("0x03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start/Stop Count.
        /// </summary>
        internal static string _0x04 {
            get {
                return ResourceManager.GetString("0x04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reallocated Sectors Count.
        /// </summary>
        internal static string _0x05 {
            get {
                return ResourceManager.GetString("0x05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Channel Margin.
        /// </summary>
        internal static string _0x06 {
            get {
                return ResourceManager.GetString("0x06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seek Error Rate.
        /// </summary>
        internal static string _0x07 {
            get {
                return ResourceManager.GetString("0x07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seek Time Performance.
        /// </summary>
        internal static string _0x08 {
            get {
                return ResourceManager.GetString("0x08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power-On Hours (POH).
        /// </summary>
        internal static string _0x09 {
            get {
                return ResourceManager.GetString("0x09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spin-Up Retry Count.
        /// </summary>
        internal static string _0x0A {
            get {
                return ResourceManager.GetString("0x0A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recalibration Retries.
        /// </summary>
        internal static string _0x0B {
            get {
                return ResourceManager.GetString("0x0B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Power Cycle Count.
        /// </summary>
        internal static string _0x0C {
            get {
                return ResourceManager.GetString("0x0C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soft Read Error Rate.
        /// </summary>
        internal static string _0x0D {
            get {
                return ResourceManager.GetString("0x0D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unused Reserved Block Count Total.
        /// </summary>
        internal static string _0xB4 {
            get {
                return ResourceManager.GetString("0xB4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SATA Downshift Error Count.
        /// </summary>
        internal static string _0xB7 {
            get {
                return ResourceManager.GetString("0xB7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End-to-End error.
        /// </summary>
        internal static string _0xB8 {
            get {
                return ResourceManager.GetString("0xB8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Head Stability.
        /// </summary>
        internal static string _0xB9 {
            get {
                return ResourceManager.GetString("0xB9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Induced Op-Vibration Detection.
        /// </summary>
        internal static string _0xBA {
            get {
                return ResourceManager.GetString("0xBA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reported Uncorrectable Errors.
        /// </summary>
        internal static string _0xBB {
            get {
                return ResourceManager.GetString("0xBB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command Timeout.
        /// </summary>
        internal static string _0xBC {
            get {
                return ResourceManager.GetString("0xBC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Fly Writes.
        /// </summary>
        internal static string _0xBD {
            get {
                return ResourceManager.GetString("0xBD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature Difference from 100.
        /// </summary>
        internal static string _0xBE {
            get {
                return ResourceManager.GetString("0xBE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G-sense error rate.
        /// </summary>
        internal static string _0xBF {
            get {
                return ResourceManager.GetString("0xBF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power-off retract count / Emergency Retract Cycle Count (Fujitsu).
        /// </summary>
        internal static string _0xC0 {
            get {
                return ResourceManager.GetString("0xC0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Cycle Count / Load/Unload Cycle Count (Fujitsu).
        /// </summary>
        internal static string _0xC1 {
            get {
                return ResourceManager.GetString("0xC1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HDA temperature.
        /// </summary>
        internal static string _0xC2 {
            get {
                return ResourceManager.GetString("0xC2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hardware ECC Recovered.
        /// </summary>
        internal static string _0xC3 {
            get {
                return ResourceManager.GetString("0xC3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reallocation Event Count.
        /// </summary>
        internal static string _0xC4 {
            get {
                return ResourceManager.GetString("0xC4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Pending Sector Count.
        /// </summary>
        internal static string _0xC5 {
            get {
                return ResourceManager.GetString("0xC5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uncorrectable Sector Count.
        /// </summary>
        internal static string _0xC6 {
            get {
                return ResourceManager.GetString("0xC6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UltraDMA CRC Error Count.
        /// </summary>
        internal static string _0xC7 {
            get {
                return ResourceManager.GetString("0xC7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write Error Rate / Multi-Zone Error Rate.
        /// </summary>
        internal static string _0xC8 {
            get {
                return ResourceManager.GetString("0xC8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soft read error rate.
        /// </summary>
        internal static string _0xC9 {
            get {
                return ResourceManager.GetString("0xC9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Address Mark errors.
        /// </summary>
        internal static string _0xCA {
            get {
                return ResourceManager.GetString("0xCA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run out cancel.
        /// </summary>
        internal static string _0xCB {
            get {
                return ResourceManager.GetString("0xCB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soft ECC correction.
        /// </summary>
        internal static string _0xCC {
            get {
                return ResourceManager.GetString("0xCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thermal asperity rate (TAR).
        /// </summary>
        internal static string _0xCD {
            get {
                return ResourceManager.GetString("0xCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flying height.
        /// </summary>
        internal static string _0xCE {
            get {
                return ResourceManager.GetString("0xCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spin high current.
        /// </summary>
        internal static string _0xCF {
            get {
                return ResourceManager.GetString("0xCF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spin buzz.
        /// </summary>
        internal static string _0xD0 {
            get {
                return ResourceManager.GetString("0xD0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline seek performance.
        /// </summary>
        internal static string _0xD1 {
            get {
                return ResourceManager.GetString("0xD1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vibration During Write.
        /// </summary>
        internal static string _0xD2 {
            get {
                return ResourceManager.GetString("0xD2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vibration During Write.
        /// </summary>
        internal static string _0xD3 {
            get {
                return ResourceManager.GetString("0xD3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shock During Write.
        /// </summary>
        internal static string _0xD4 {
            get {
                return ResourceManager.GetString("0xD4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disk Shift.
        /// </summary>
        internal static string _0xDC {
            get {
                return ResourceManager.GetString("0xDC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G-Sense Error Rate.
        /// </summary>
        internal static string _0xDD {
            get {
                return ResourceManager.GetString("0xDD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded Hours.
        /// </summary>
        internal static string _0xDE {
            get {
                return ResourceManager.GetString("0xDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load/Unload Retry Count.
        /// </summary>
        internal static string _0xDF {
            get {
                return ResourceManager.GetString("0xDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Friction.
        /// </summary>
        internal static string _0xE0 {
            get {
                return ResourceManager.GetString("0xE0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Cycle Count.
        /// </summary>
        internal static string _0xE1 {
            get {
                return ResourceManager.GetString("0xE1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load &apos;In&apos;-time.
        /// </summary>
        internal static string _0xE2 {
            get {
                return ResourceManager.GetString("0xE2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Torque Amplification Count.
        /// </summary>
        internal static string _0xE3 {
            get {
                return ResourceManager.GetString("0xE3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power-Off Retract Cycle.
        /// </summary>
        internal static string _0xE4 {
            get {
                return ResourceManager.GetString("0xE4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drive Life Protection Status.
        /// </summary>
        internal static string _0xE6 {
            get {
                return ResourceManager.GetString("0xE6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature.
        /// </summary>
        internal static string _0xE7 {
            get {
                return ResourceManager.GetString("0xE7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endurance Remaining / Available Reserved Space.
        /// </summary>
        internal static string _0xE8 {
            get {
                return ResourceManager.GetString("0xE8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power-On Hours / Media Wearout Indicator.
        /// </summary>
        internal static string _0xE9 {
            get {
                return ResourceManager.GetString("0xE9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average erase count AND Maximum Erase Count.
        /// </summary>
        internal static string _0xEA {
            get {
                return ResourceManager.GetString("0xEA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good Block Count AND System(Free) Block Count.
        /// </summary>
        internal static string _0xEB {
            get {
                return ResourceManager.GetString("0xEB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Head flying hours / Transfer Error Rate (Fujitsu).
        /// </summary>
        internal static string _0xF0 {
            get {
                return ResourceManager.GetString("0xF0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total LBAs Written.
        /// </summary>
        internal static string _0xF1 {
            get {
                return ResourceManager.GetString("0xF1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total LBAs Read.
        /// </summary>
        internal static string _0xF2 {
            get {
                return ResourceManager.GetString("0xF2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Error Retry Rate.
        /// </summary>
        internal static string _0xFA {
            get {
                return ResourceManager.GetString("0xFA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free Fall Protection.
        /// </summary>
        internal static string _0xFE {
            get {
                return ResourceManager.GetString("0xFE", resourceCulture);
            }
        }
    }
}
